### ISSUE TITLE
The window.postMessage to send a chasitor event doesn't work.

### ISSUE THREAD

**Issue by erocheleau** [Colatabajonies/Chat-Lightning-Web-Component-Pack#2]
On my community or inside the bot preview, any component that are "replacing" the customer's input, for example the date picker, the survery, etc.

They all try to send a response to the bot back with 

```
window.postMessage({ message: dateValue, type: "chasitor.sendMessage" }, window.parent.location.href );
```

I see the event being fired, but nothing happens and the bot doesn't receive the customer's message so it just sits there waiting for an input.

**Comment by wilsonwong13** [comment]
Is there any documentation how 
`window.postMessage(
            {
                message: dateValue,
                type: "chasitor.sendMessage"
            },
            window.parent.location.href
        );`
works? I can't find anything at the moment

**Comment by erocheleau** [comment]
Me neither, looks like a spoof of what the actual chat window receives as an event when the customer sends a chat message?

**Comment by wilsonwong13** [comment]
@erocheleau Have you looked at the user guide yet? https://quip.com/WM7AA3tXRsaf

**Comment by erocheleau** [comment]
I have found it afterwards yes, my bad.

But is there no other way to support this? As someone who wants to distribute a managed package using this feature, it is not really realistic to ask every client to copy a JS snippet in the header of their community.

You can close this as it isn't really related to this package anymore, but perhaps you could add that quip link to the readme?

**Comment by forcePanda** [comment]
Is there any other way to post the message as chasitor from the LWC to the bot?
I don't want to do:
`window.postMessage({ message: dateValue, type: "chasitor.sendMessage" }, window.parent.location.href );`

And use the script in the community page header.

**Comment by HardikaDoshi** [comment]
Hi, 
when I try out this event, it gives a error message in the console 
`aura_prod.js:21 Uncaught TypeError: Cannot read properties of undefined (reading 'href')`

has anyone found a solution for this?

**Comment by erocheleau** [comment]
This issue was resolved after reading the documentation :)
