### ISSUE TITLE
Flow response is currently not working

### ISSUE THREAD

**Issue by wilsonwong13** [Colatabajonies/Chat-Lightning-Web-Component-Pack#3]
Docs that was used - https://quip.com/WM7AA3tXRsaf, followed 5d and e steps
**Current result**: 
![Screen Shot 2020-08-19 at 4 24 48 PM](https://user-images.githubusercontent.com/23243527/90686052-bf139900-e238-11ea-9517-c7fea6259f40.png)
\
Setup:

**Flow is Active**
![Screen Shot 2020-08-19 at 4 24 31 PM](https://user-images.githubusercontent.com/23243527/90686071-c89d0100-e238-11ea-9112-e33b30f2c72e.png)

**Community Page Setup**: 
![Screen Shot 2020-08-19 at 4 28 19 PM](https://user-images.githubusercontent.com/23243527/90686232-0863e880-e239-11ea-991e-264d2c8aa85e.png)

**Comment by wilsonwong13** [comment]
Resolve: Edit the question dialog for the flow to account for namespace
lwc:flow:CLWCP__Test_Flow_for_Chat:350

**Comment by Velvizhi15** [comment]
Can you please help me as well for using flow inside bot
